theme: minima
github: [metadata]
title: Nicole Cai 
encoding: UTF-8
permalink: /:title/
markdown: kramdown
include: ['_pages']
# collections:
#   post_drafts:
#     output: true
#gems:
#  - jekyll-feed
exclude:
  - README.md
header_pages:
  - _pages/pubs.md
#  - _pages/news.md
google:
    analytics_id:G-HDE76W1ESS
